name: Build and Push Docker Image

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/**"
      - "**/*.js"
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=jhona1dev/api_node_actions
          TAG=latest
          docker build -t $IMAGE:$TAG -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:$TAG
          docker push $IMAGE:${{ github.sha }}
          echo "Docker image pushed: $IMAGE:$TAG and $IMAGE:${{ github.sha }}"